### ISSUE TITLE
smart-mode-line integration?

### ISSUE THREAD

**Issue by unhammer** [tarsius/moody#1]
Hi, this is quite a nice modeline :-) Is there a way to get the buffer-identification stuff from https://github.com/Malabarba/smart-mode-line/ into it? Right now, it only shows the buffer name, not the full abbreviated path.

**Comment by tarsius** [comment]
I was actually using `smart-mode-line` before I wrote this and there already was some code to do what you are asking but it didn't quite work and was marked as FIXME. I have now looked into this again and (force) pushed the result.

Just use `(moody-replace-sml/mode-line-buffer-identification)` after loading that package but without runnin `sml/setup`. That's how I intend to use it for a while. I don't like how sml's displays minor-modes - that still uses too much space. (I have started writing a replacement: https://github.com/tarsius/minions). And I don't care that much for the other improvements that it provides.

Never-the-less running `sml/setup` seems to be compatible with the above setting.

**Comment by unhammer** [comment]
https://github.com/tarsius/moody/commit/2ac72b7a4a759d4c3dc9f7187ecd20062656d09e#diff-b7a50c95993395f1649123f0d350ce93 gives me
`Eager macro-expansion failure: (wrong-number-of-arguments (3 . 5) 6)`
`moody.el:176:1:Error: Wrong number of arguments: (3 . 5), 6
`

**Comment by tarsius** [comment]
I have pushed a new version since then. By the way I have also pushed a "final" `Initial import` now. :wink:

**Comment by unhammer** [comment]
Hm, maybe github is not picking it up – https://github.com/tarsius/moody still says 2ac72b7 for me

**Comment by tarsius** [comment]
Ah sorry I looked at the wrong part of the url. That's the latest version. But are you sure you are loading the that version as opposed to some outdated byte-code? I remember that error, it was due to the `VAL` of a `setf` missing, but I fixed that.

**Comment by tarsius** [comment]
But just in case, I have just created one more (now hopefully really final) `Initial import`.

**Comment by unhammer** [comment]
```
$ git log 
commit 2ac72b7a4a759d4c3dc9f7187ecd20062656d09e (HEAD -> master, origin/master, origin/HEAD)
Author: Jonas Bernoulli <jonas@bernoul.li>
Date:   Thu Feb 8 16:22:45 2018 +0100

    Initial import
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working tree clean
$ emacs -Q --batch --eval '(byte-compile-file "moody.el")'

In toplevel form:
moody.el:176:1:Error: Wrong number of arguments: (3 . 5), 6

```

**Comment by tarsius** [comment]
What Emacs version?

**Comment by unhammer** [comment]
GNU Emacs 25.3.2

**Comment by tarsius** [comment]
Ah now I remember, `alist-get` changed.

```
emacs-25.3 -Q --batch --eval '(byte-compile-file "moody.el")' 

In toplevel form:
moody.el:176:1:Error: Wrong number of arguments: (3 . 5), 6
```

**Comment by tarsius** [comment]
The new TESTFN argument is important here, otherwise `eql` would be used. And I want to use `alist-get` because otherwise I would have to replace that single form with several lines of "what's going on there".

**Comment by tarsius** [comment]
Okay since we actually just checked that there is no existing entry we can just `push` the new one.

**Comment by unhammer** [comment]
OK, I should probably wait for emacs 26 then, saw it's slated for release Soon™ :-)

**Comment by tarsius** [comment]
No no, I just pushed two new commits. LIke, actual new commits, no more `--amend` crap :stuck_out_tongue_winking_eye:

**Comment by tarsius** [comment]
> it's slated for release Soon™ 

Is it?

**Comment by unhammer** [comment]
according to random redditors, yes =P
