### ISSUE TITLE
Top right of ribbon down is missing its border

### ISSUE THREAD

**Issue by Koekelas** [tarsius/moody#10]
They say a picture is worth a thousand words. Look at the top right of ribbon down. Its border is missing. I made `:underline` and `:overline` red so it's easier to see.

![Image of missing border](https://user-images.githubusercontent.com/6143998/37469816-709f2796-2866-11e8-944d-1405b941077a.png)

In case you'd like the above mode line format:
```emacs-lisp
(setq mode-line-format
      '(" "
        (:eval
         (moody-tab "Tab down"))
        " "
        (:eval
         (moody-tab "Tap up" 0 'up))
        " "
        (:eval
         (moody-ribbon "Ribbon down"))
        " "
        (:eval
         (moody-ribbon "Ribbon up" 0 'up))))
```

Thank you for making moody.

**Comment by tarsius** [comment]
Thanks!

**Comment by Koekelas** [comment]
Looks correct now. Thank you for the speedy fix.
