### ISSUE TITLE
Glitch on multiple windows

### ISSUE THREAD

**Issue by manuel-uberti** [tarsius/moody#15]
An image speaks more than my words :)

![screenshot](https://user-images.githubusercontent.com/8199224/38189004-7f90f6fc-365e-11e8-866f-58ceb1c31d26.png)

This only happens with 3 windows, no problem with 2 windows.

**Comment by tarsius** [comment]
Simply having tree windows in a frame (which I hardly ever do) does not seem to be enough to trigger this issue. Does this always happen for you? What Emacs version do you use etc.?

The implementation is pretty simply.
1. On certain events (hooks and advices) `moody--set-active-window`.
2. When a mode-line is being redisplayed, then `moody-slant` (the function responsible for creating the images) calls `moody-window-active-p` to check whether the selected window is the active window.

So the most likely cause for this is that the mode-line is not being redisplayed. We have to figure out under what circumstances that happens.

**Comment by manuel-uberti** [comment]
More details:

- Emacs version: GNU Emacs 27.0.50 (build 1, x86_64-debian-linux-gnu, GTK+ Version 3.18.9) of 2018-04-03
- `moody` version: latest from MELPA

You're right. The problem only happens when, like in the screenshot above, one of the 3 windows is a PDF files displayed with `pdf-tools`.

However, it does not happen with 2 windows and one of them is displaying the same PDF file via `pdf-tools`.

**Comment by manuel-uberti** [comment]
Another detail, if it could help: if I press ALT+TAB to switch to another window outside Emacs and then ALT+TAB again, the glitch disappears.

**Comment by manuel-uberti** [comment]
Since it is happening only when viewing a PDF file with `pdf-tools`, do you think we can close this issue? I can always open a new one on `pdf-tools` repository.

**Comment by NateEag** [comment]
I'll add that I see the same issue in [my config](https://github.com/NateEag/.emacs.d), but in my case it's triggered by having a Helm buffer open in the other window.

I think you can reproduce it by starting Emacs using my config, making a frame with two windows, then doing `C-x C-f`, if you care to.

Just figured I'd add the data point.

**Comment by tarsius** [comment]
"Here is my config" does not constitute minimal steps necessary to reproduce an issue ;-)

Anyway, this happens to me too occasionally and I will eventually get around to fix it, but so far it doesn't bother me enough to prioritize it.

**Comment by NateEag** [comment]
Yup, I know, and it wasn't intended to be.

I just thought the additional info might be useful if someone decided to dig into this.

**Comment by tarsius** [comment]
I have applied some of the commits from #20 and the above no longer happens as far as I can tell.

**Comment by manuel-uberti** [comment]
Thanks for the fix. I'll do some tests and report back if anything's wrong.
