### ISSUE TITLE
Setting the correct value for mode-line-format and mode-line-buffer-identification for treemacs buffers?

### ISSUE THREAD

**Issue by CSRaghunandan** [tarsius/moody#17]
<img width="637" alt="screen shot 2018-06-01 at 5 52 36 pm" src="https://user-images.githubusercontent.com/5226809/40870265-746835c2-6649-11e8-9af5-d88ce531578b.png">

This is how treemacs mode-line looks when I enable it. I tried modifying the `mode-line-format` to contain `mode-line-buffer-indentification` and `vc-mode`, but no matter what  I try, I'm unable to get moody mode-line to work on treemacs window :( 

Relevant discussion in Treemacs issue tracker: https://github.com/Alexander-Miller/treemacs/issues/204

**Comment by tarsius** [comment]
When using moody, the height of the mode-line is controlled by the height of the slope images. That of course assumes that `mode-line-format` contains any slope images.

> I tried modifying the `mode-line-format` to contain `mode-line-buffer-indentification` and `vc-mode`

I don't see any signs of that in your screenshot and would assume that if you managed to insert slope images into the format used for the treemacs buffer, then the mode-line's height would be increased for that buffer also.

I haven't tested this, but this should do the trick:

```lisp

(defun treemacs--setup-mode-line ()
  "Create either a simple modeline, or integrate into spaceline."
  (setq mode-line-format
        (cond ((fboundp 'spaceline-install)
               (spaceline-install
                "treemacs" '((workspace-number
                              :face highlight-face)
                             major-mode)
                nil)
               '("%e" (:eval (spaceline-ml-treemacs))))
              ((memq 'moody-mode-line-buffer-identification
                     (default-value 'mode-line-format))
               '(:eval (moody-tab " Treemacs " 10 'down)))
              (t
               '(" Treemacs ")))))
```

**Comment by CSRaghunandan** [comment]
Yes, that works perfectly for treemacs buffer. 
Thank you

**Comment by tarsius** [comment]
Please open a treemacs pr with that code then. Thanks!
