### ISSUE TITLE
Invisible buffer name in leuven-theme

### ISSUE THREAD

**Issue by yiufung** [tarsius/moody#22]
When I use leuven-theme, buffer name is invisible on modeline. 

![screenshot_2019-01-16_10-29-03](https://user-images.githubusercontent.com/1023375/51222728-f85b9700-1979-11e9-8d14-ef2846518c1c.png)

It becomes yellow when I hover the mouse above. Here's a [minimal reproducible config](https://gist.github.com/yiufung/0a54019a96fa9032923e98cf572280e0). 

Version info: 
```
GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-07-05
Org mode version 9.2 (9.2-elpaplus @ /home/yiufung/.cyf-emacs/elpa/org-plus-contrib-20181230/)
```

**Comment by tarsius** [comment]
1. `leuven-theme` uses the same color (white) as the foreground color of the buffer identification as it uses as the background color of buffers (i.e. of the `default` face).

2. `moody` uses the the same color as the background color of "tabs" as is used as the background color of the buffer/`default`. If `leuven-theme` is used, then that is white.

3. 1+2= white on white, which is an incompatibility not a bug.

It is obvious how that incompatibility has to be addressed: the *user* has to change the foreground color of `mode-line-buffer-id` to be something that is visible on a white background.

**Comment by yiufung** [comment]
Many thanks for the detailed explanation! Now it works.
