### ISSUE TITLE
(setq moody-slant-function 'moody-slant-apple-rgb) causes Error during redisplay

### ISSUE THREAD

**Issue by thepreacher** [tarsius/moody#23]
With `(setq moody-slant-function 'moody-slant-apple-rgb)` in the config, I get the following error multiple times in the **messages** buffer. 

The errors disappear when I comment it out.

`Error during redisplay: (eval (moody-tab (format-mode-line (propertized-buffer-identification "%b")) 20 (quote down))) signaled (wrong-type-argument number-or-marker-p nil) [2 times]`

Below is my whole **minions / moody** config:

```
;; A minor-mode menu for the mode line
(use-package minions
  :ensure t
  :config
  (setq
    minions-mode-line-lighter "[+]"
    minions-direct '(flycheck-mode pyvenv-mode))
  (minions-mode 1))

;; Tabs and ribbons for the mode line
(use-package moody
  :ensure t
  :config
  (setq x-underline-at-descent-line t
        moody-mode-line-height 25)
        ;;moody-slant-function #'moody-slant-apple-rgb)
  (moody-replace-mode-line-buffer-identification)
  (moody-replace-vc-mode))

```

**Comment by thepreacher** [comment]
@tarsius following your comment and commit, I updated moody and tried again with `(setq         moody-slant-function #'moody-slant-apple-rgb)` uncommented and the error still persists. I use the `dracula-theme` with the following config:

```
;; Theme
(use-package dracula-theme
  :ensure t
  :config
  (load-theme 'dracula t)
  (let ((line (face-attribute 'mode-line :underline)))
    (set-face-attribute 'mode-line          nil :overline   line)
    (set-face-attribute 'mode-line-inactive nil :overline   line)
    (set-face-attribute 'mode-line-inactive nil :underline  line)
    (set-face-attribute 'mode-line          nil :box        nil)
    (set-face-attribute 'mode-line-inactive nil :box        nil)
    (set-face-attribute 'mode-line-inactive nil :background "#f9f2d9")))
```
Thanks btw for taking the time.

**Comment by tarsius** [comment]
Add a debug statement `(message "%s %s %s" c1 c2 c3)` to `moody-slant-apple-rgb` so that we can know for sure whether the values that go in are what we would expect.

**Comment by thepreacher** [comment]
@tarsius don't know if I did what you expected but I added `(message "%s %s %s c1 c2 c3)` to the `moody-slant-apple-rgb` function in a local copy of moody.el and loaded that instead of the one installed from melpa? Anyway below is what got from `Messages` buffer

```
Error during redisplay: (eval (moody-tab (format-mode-line (propertized-buffer-identification "%b")) 20 (quote down))) signaled (wrong-type-argument number-or-marker-p nil) [2 times]
#44475a #44475a #282a36 [180 times]
```
What was different from the original message are these 3 values `#44475a #44475a #282a36`. Is that what you were expecting? Sorry but I can only understand the basic of elisp code.

**Comment by tarsius** [comment]
Yes that's what I wanted you to do. But the result is unexpected. What was the line right before the `Error duing redisplay` line? Something like `#44475a #44475a nil`?

**Comment by tarsius** [comment]
I think `M-x toggle-debug-on-error` does not give us a backtrace for errors that occur during redisplay, but give it a try anyway.

**Comment by thepreacher** [comment]
Below is a capture of the last few consecutive error listings in the `Messages` buffer:

```
Error during redisplay: (eval (moody-tab (format-mode-line (propertized-buffer-identification "%b")) 20 (quote down))) signaled (wrong-type-argument number-or-marker-p nil) [5 times]
#44475a #44475a #282a36 [12 times]
mwheel-scroll: End of bufferError during redisplay: (eval (moody-tab (format-mode-line (propertized-buffer-identification "%b")) 20 (quote down))) signaled (wrong-type-argument number-or-marker-p nil)
Error during redisplay: (eval (moody-tab (format-mode-line (propertized-buffer-identification "%b")) 20 (quote down))) signaled (wrong-type-argument number-or-marker-p nil) [5 times]
#44475a #44475a #282a36 [18 times]
mwheel-scroll: End of bufferError during redisplay: (eval (moody-tab (format-mode-line (propertized-buffer-identification "%b")) 20 (quote down))) signaled (wrong-type-argument number-or-marker-p nil)
Error during redisplay: (eval (moody-tab (format-mode-line (propertized-buffer-identification "%b")) 20 (quote down))) signaled (wrong-type-argument number-or-marker-p nil) [4 times]
#44475a #44475a #282a36 [398 times]

```

I set `(setq debug-on-error t)` but as you mentioned that didn't yeild any backtrace.

**Comment by tarsius** [comment]
Evaluate `moody-slant-apple-rgb` manually, while debugging is enabled, passing it the arguments that it is passed when being called when updating the mode-line. To get those arguments update the debug statement from earlier to print all arguments. You should use "%S" instead of "%s".

By the way, I am not sure the error occurs in that function, but since you said this error occurs when using it, I am going with that for now.

**Comment by tarsius** [comment]
I have installed the relevant packages in a clean environment and used your configuration. I don't get any errors. Maybe one of the `color-*` functions used by `moody-slant-apple-rgb` has a bug on macOS (I tested on Linux).

You will have to figure out where something that is supposed to be a number actually is nil. My suggestion is to add debug statements until you have narrowed the issue down. Or maybe the issue is caused by some other package or your configuration. So start by trying the reproduce the issue with just `moody`, then add the theme and your configuration for the theme and moody to the mix... At some point it will start breaking and then you can look at the thing that you have just added in more detail.

**Comment by thepreacher** [comment]
@tarsius your are right! I disabled the theme `dracula` and the error message(s) are gone. Very sorry for wasting your time. I'll have to look a compatible theme that I like then.

**Comment by tarsius** [comment]
It worked for me with dracula-theme.

**Comment by thepreacher** [comment]
Maybe it's a macOS thing with dracula-theme because I tried tomorrow-night and solarized both worked fine although I'm not very fond of any of them. Anyway will leave this issue opened for a few more hours just in case.
