### ISSUE TITLE
How do I insert a variable into a moody tab?

### ISSUE THREAD

**Issue by grolongo** [tarsius/moody#26]
Hello,

I'm trying to understand how I can personalize a bit the moody mode line.

For example, I want the variable `evil-mode-line-tag` (which shows if I'm in normal, insert or visual mode) to appear into a moody tab.

I found I can do this by rewriting the whole `mode-line-format` (I've shorten the code for the example):

```
:custom 
(mode-line-format                        
 '(" "                                   
   (:eval                                
    (moody-wrap "%b"))                   
   " "                                   
   (:eval                                
    (moody-tab evil-mode-line-tag 0 'up))

   etc.
```

It works fine, but is there not a better way that I'm missing? Like something that I can configurate on one line which says "take the `evil-mode-line-tag` and put it into a tab", instead of rewriting the whole `mode-line-format` like above?

Thanks for your help.

**Comment by tarsius** [comment]
Copy the code that deals with the `buffer-identification`:

```emacs-lisp
(defvar moody-mode-line-buffer-identification
  '(:eval (moody-tab (format-mode-line (propertized-buffer-identification "%b"))
                     20 'down)))
(put 'moody-mode-line-buffer-identification 'risky-local-variable t)
(make-variable-buffer-local 'moody-mode-line-buffer-identification)

;;;###autoload
(defun moody-replace-mode-line-buffer-identification (&optional reverse)
  (interactive "P")
  (moody-replace-element 'mode-line-buffer-identification
                         'moody-mode-line-buffer-identification
                         reverse))
```

Edit that code to do the equivalent thing for `evil-mode-line-tag`.

**Comment by grolongo** [comment]
Thank you for the solution tarsius, I'll do!
