### ISSUE TITLE
Emacs 28 mode-line-compact distorts styling

### ISSUE THREAD

**Issue by protesilaos** [tarsius/moody#28]
Hello Jonas!  I noticed that `(setq mode-line-compact nil)` (Emacs 28) has a negative effect on Moody: it eliminates the spaces that are used to draw the diagonal lines of e.g. `moody-replace-mode-line-buffer-identification`.  Just thought I would bring this to your attention.

**Comment by tarsius** [comment]
Thanks for the report!

**Comment by protesilaos** [comment]
You are welcome!  And thanks for the quick fix.
