### ISSUE TITLE
:scale 1 causes xpm error

### ISSUE THREAD

**Issue by ambihelical** [tarsius/moody#30]
Updating emacs packages after a long hiatus, I found the following change in moody doesn't agree with emacs 27.1, Ubuntu 16.04.7, Emacs built from source:

https://github.com/tarsius/moody/commit/f6bebfe6fe51b728ebd013b7084becad23cabad3

This causes many messages like this:
```
Color allocation error ((image :type xpm :data /* XPM */ static char * image[] = {
 "15 30 3 1",
 "0 c #d7d7d7",
 "1 c nil",
 "2 c #ffffff", "2222222222222221",
 "2222222222222210",
 "2222222222222210",
 "2222222222222100",
 "2222222222222100",
 "2222222222221000",
 "2222222222221000",
 "2222222222210000",
 "2222222222210000",
 "2222222222100000",
 "2222222222100000",
 "2222222221000000",
 "2222222221000000",
 "2222222210000000",
 "2222222210000000",
 "2222222100000000",
 "2222222100000000",
 "2222221000000000",
 "2222221000000000",
 "2222210000000000",
 "2222210000000000",
 "2222100000000000",
 "2222100000000000",
 "2221000000000000",
 "2221000000000000",
 "2210000000000000",
 "2210000000000000",
 "2100000000000000",
 "2100000000000000",
 "1000000000000000",

}; :scale 1 :ascent center))
```

Changing this to just :scale (without parameter) gets rid of the problem, but I have no idea if this is the correct fix.

**Comment by ambihelical** [comment]
I'm guessing that's not the right fix because the diagonal folder tabs are missing.  If I just remove :scale 1 altogether, they reappear.

**Comment by tarsius** [comment]
I would guess that it's actually this part that is the problem: `"1 c nil"`. That's supposed to be a color.

The colors are determined using the `:background` and `:underline` properties of `face-active` and `face-inactive`. Make sure those are set.

**Comment by ambihelical** [comment]
You are right.  Modus theme configuration changed under me and wasn't loading correctly. Fixing that no longer requires any changes to moody.
