### ISSUE TITLE
No line around ribbons for some themes

### ISSUE THREAD

**Issue by tobiasBora** [tarsius/moody#38]
If I load first the `solarized-theme` and then `doom-nord-light`, I get a nice modline:

![image](https://user-images.githubusercontent.com/2164118/147945274-9d7a8604-dee1-4211-8641-eb574c174115.png)

Unfortunately, if I only load `doom-nord-light` I get an ugly modling (the line around ribbons is missing). What am I doing wrong?

![image](https://user-images.githubusercontent.com/2164118/147945626-f6043aa5-7b94-4b58-a4a2-4f39342ded42.png)

**Comment by tarsius** [comment]
The theme `doom-nord-line` doesn't set overline/underline for the relevant faces. You therefore have to customize them yourself. The readme contains instructions about that.

**Comment by tobiasBora** [comment]
Thanks for your answer, and sorry to bother you. I did read the README but I just copy/pasted the code naively. In fact, we need to redefine `line` since as you say the theme does not provide underline and `line` is defined with respect to it. It way worth clarifying that in the readme by providing a working code for inexperienced users. 

I tried the following code which works nicely:
```
(use-package doom-themes
  :ensure t
  :config
  ;; Global settings (defaults)
  (setq doom-themes-enable-bold t    ; if nil, bold is universally disabled
        doom-themes-enable-italic t) ; if nil, italics is universally disabled
  (load-theme 'doom-nord-light t)

  ;; Enable flashing mode-line on errors
  (doom-themes-visual-bell-config)
  ;; Enable custom neotree theme (all-the-icons must be installed!)
  ;; (doom-themes-neotree-config)
  ;; or for treemacs users
  ;; (setq doom-themes-treemacs-theme "doom-atom") ; use "doom-colors" for less minimal icon theme
  ;; (doom-themes-treemacs-config)
  ;; Corrects (and improves) org-mode's native fontification.
  (doom-themes-org-config)
  ;; Remove ugly lines on the side https://emacs.stackexchange.com/questions/69983/how-to-change-the-color-or-remove-the-line-next-to-the-scroll-bar/69984#69984
  (custom-set-faces
   `(fringe ((nil))))
  ;; Inspired by https://github.com/tarsius/moody
  (let ((line "#cccec4"))
    (set-face-attribute 'mode-line          nil :overline   line) ;; line refers to the line right above
    (set-face-attribute 'mode-line-inactive nil :overline   line)
    (set-face-attribute 'mode-line          nil :underline  line)
    (set-face-attribute 'mode-line-inactive nil :underline  line)
    (set-face-attribute 'mode-line          nil :box        nil)
    (set-face-attribute 'mode-line-inactive nil :box        nil)
    (set-face-attribute 'mode-line          nil :background "#d4def0");; Color of the modeline
    (set-face-attribute 'mode-line-inactive nil :background "#d4def0"));; Color of the modeline
  )
```

**Comment by tarsius** [comment]
I've added a note about that.

**Comment by tobiasBora** [comment]
Thanks a lot!
