### ISSUE TITLE
Not working with solarized 

### ISSUE THREAD

**Issue by anoopd** [tarsius/moody#45]
Here is my config 
``` (use-package solarized-theme
     :straight t
     :config
     (load-theme 'solarized-light t)
     (let ((line (face-attribute 'mode-line :underline)))
	(set-face-attribute 'mode-line          nil :overline   line)
	(set-face-attribute 'mode-line-inactive nil :overline   line)
	(set-face-attribute 'mode-line-inactive nil :underline  line)
	(set-face-attribute 'mode-line          nil :box        nil)
	(set-face-attribute 'mode-line-inactive nil :box        nil)
	(set-face-attribute 'mode-line-inactive nil :background "#f9f2d9")))
    
(use-package moody
  :straight t
  :config
  (setq x-underline-at-descent-line t)
  (moody-replace-mode-line-buffer-identification)
  (moody-replace-vc-mode)
  (moody-replace-eldoc-minibuffer-message-function))
```
But it is not working ?  When i run `eval-buffer` it is showing `cannot find (vc-mode vc-mode) and use (vc-mode moody-vc-mode) in its place` .  Can somebody point out what i have done wrong ?

**Comment by tarsius** [comment]
Themes only change the colors and such, so the used theme is irrelevant here.

Moody replaces certain elements of `mode-line-format` with certain other elements. The above error indicates that an element that it expected to find there, wasn't actually there. The cause for this is that some other package (not the theme) or your configuration removed that element. I guess it is one of the packages that I classify as all-or-nothing mode-line packages, see https://github.com/tarsius/moody/wiki#it-doesnt-work.

**Comment by anoopd** [comment]
Thank you and i will check it
