### ISSUE TITLE
moody-ribbon-background showing next to VC mode element

### ISSUE THREAD

**Issue by tmtvl** [tarsius/moody#46]
When the VC mode element in the modeline gets replaced I am seeing an area of the modeline being shown in the style of moody-ribbon-background.  To make it extra clear I have set moody-ribbon-background to a combination of elements that stands out:

![moody-ribbon-background-poking-through](https://user-images.githubusercontent.com/1783407/203835011-5c8a6023-7572-4e69-b06d-1da2ac6d7daa.png)

I'm on the most recent commit on master.

**Comment by tarsius** [comment]
Did you use `moody-replace-vc-mode`?

This is my setup, which doesn't do that:

```elisp
(use-package moody
  :when (and (version<= "25.3" emacs-version)
             (display-graphic-p))
  :config
  (moody-replace-mode-line-front-space)
  (moody-replace-mode-line-buffer-identification)
  (moody-replace-vc-mode)
  (moody-replace-eldoc-minibuffer-message-function))
```

**Comment by tmtvl** [comment]
Yes, my setup is as follows:

```emacs-lisp
(let ((line "#505050"))
    (set-face-attribute 'mode-line nil :overline line)
    (set-face-attribute 'mode-line nil :underline line)
    (set-face-attribute 'mode-line-inactive nil :overline line)
    (set-face-attribute 'mode-line-inactive nil :underline line)
    (set-face-attribute 'mode-line nil :box nil)
    (set-face-attribute 'mode-line-inactive nil :box nil)
    (set-face-attribute 'mode-line-buffer-id
                        nil
                        :background
                        (face-attribute 'mode-line :background))
    (set-face-attribute 'mode-line-emphasis
                        nil
                        :background
                        (face-attribute 'mode-line :background)))

(moody-replace-mode-line-buffer-identification)
(moody-replace-vc-mode)
(moody-replace-eldoc-minibuffer-message-function)
```

**Comment by tmtvl** [comment]
I found the problem, it seems like the issue is that I have the `modus-themes-variable-pitch-ui` option set.  Without that option I am not getting the empty space next to the VC ribbon.  I suppose the solution would be not to use that option together with `moody-replace-vc-mode`.

**Comment by tarsius** [comment]
That rings a bell. If I remember correctly, this happens when there are two consecutive spaces and variable-pitch is used. So not using variable-pitch is one solution, but the other is to remove all double spaced from `mode-line-format`. I couldn't quickly find the place where the weird behavior is implemented.

**Comment by tmtvl** [comment]
Got it, thanks for the help!
