### ISSUE TITLE
Dynamic height

### ISSUE THREAD

**Issue by max-arnold** [tarsius/moody#47]
I set `moody-mode-line-height` to `18`, but when I scale the default font via `C-x C-M-+` (`global-text-scale-adjust`), it produces modeline artifacts around moody slants.

Is there a way to calculate the height dynamically? It seems the default `defcustom` expression is evaluated once

**Comment by tarsius** [comment]
Did you try setting the option to nil? In that case `window-mode-line-height` is used.

**Comment by max-arnold** [comment]
Just tried that and personally I'd like it to be slightly less tall

**Comment by tarsius** [comment]
> Just tried that and personally I'd like it to be slightly less tall

The result of what I suggested is that the mode-line becomes *less* tall -- the bare minimum to not truncate the text. You probably did not create a new window to observe the actual effect. I would recommend you set the variable in your init file (before moody is loaded), and then restart Emacs.

**Comment by tarsius** [comment]
Automatically scaling the height might be more involved than this though.

**Comment by tarsius** [comment]
I won't have time to work on this until next year, but you can experiment yourself. You can write your own function which wraps `moody-slant` and set that as `moody-slant-function`. Your function should forward its own arguments to `moody-slant` but additionally can pass the `height` argument, which can be the result of any calculation you fancy. You might also have to use `(force-mode-line-update t)`, when the size of faces changes.
