### ISSUE TITLE
Faulty rendering on HiDPI screen

### ISSUE THREAD

**Issue by manuel-uberti** [tarsius/moody#7]
Hi,

this is what I get on the 3200x1800 display's resolution of my Dell XPS 13.

![modeline](https://user-images.githubusercontent.com/8199224/37255100-dba31b6e-2547-11e8-945c-20e6332e3550.png)

Everything works fine with the external monitor (1920x1080).

I am using Ubuntu 16.04 LTS, with latest `moody` from MELPA on GNU Emacs 27.0.50 (build 1, x86_64-debian-linux-gnu, GTK+ Version 3.18.9) of 2018-03-11.

If you need more tests or details, feel free to ask.

**Comment by manuel-uberti** [comment]
Changing the laptop screen resolution to 1920x1080 fixes it, but I wonder if there is something better to do.

I tried building Emacs with the Lucid toolkit, same problem.

**Comment by tarsius** [comment]
That's probably because `moody-mode-line-height`'s default value is 30.

Could you please figure out how to do get the height of a font in pixels? `(face-attribute 'mode-line :height)` returns something else.

**Comment by manuel-uberti** [comment]
Something like this:
```
(aref (font-info (face-font 'default)) 2)
```
returns `40` on my setup. If I then do:
```
(set-frame-font "Iosevka:pixelsize=40")
```
I get the same as doing:
```
(set-face-attribute 'default nil
                    :family "Iosevka"
                    :height 150)
```

**Comment by tarsius** [comment]
Yep. 43afb6d185a6ced831e7460c374b563bf7504ff6 should do the trick.

**Comment by manuel-uberti** [comment]
Yes, fantastic, works beautifully on both displays now. Thank you!
