### ISSUE TITLE
Right align mode-line-misc-info

### ISSUE THREAD

**Issue by dakra** [tarsius/moody#8]
I really like moody with minions but I would like to be able to right align
`mode-line-misc-info` and `minions` (/`mode-line-modes`).
That's the only feature I'm currently missing from smart-mode-lines.
I saw https://emacs.stackexchange.com/a/7542/12559 but it doesn't seem to work
with my setup.

**Comment by tarsius** [comment]
Well, I want my mode-line packages to do one thing and one thing only. The feature you are asking for is something I would like to implement eventually, but so far I have only come up with a name: `lemming`.

` -:***- \  moody.el  / 20% (83,11) / Git-master \` ![blocker lemming](https://user-images.githubusercontent.com/25046/37493710-2f9ad0fc-28a6-11e8-9374-544cc5bfbd03.png) ` (Emacs-lisp ;-)`

**Comment by tarsius** [comment]
Closing in favor of https://github.com/tarsius/lemming ;-)
